### ISSUE TITLE
[fix]: Component tag handling

### ISSUE THREAD

**Issue by Hammster** [posthtml/posthtml-render#18]
Using the posthtml-renderer in combination with Vue is only partially possible, dynamic components that use the `component` tag are not rendered properly. Those tags that are defined as singular tags are not necessarily singular tags depending on the context that they are beeing used.

It would be good to have a way to exclude a tag from the singluar tags instead of only allowing additions.

### `Details`

- Parcel.js added vue support in 1.7.0 and posthtml is part of the html pipeline. 
- Vue's component tag can contain content
- The output of posthtml-renderer stripes the tag content and does not close the tag.
- I tried my luck with the `closingSingleTag` option but this sadly removed the content too.
- I openened up parcel-bundler/parcel/issues/1089

### `Reproduction (Code)`

```js
const render = require('posthtml-render')

// this is the generated AST from within parcel.js
const markup = {
    "tag": "component",
    "attrs": {
        "class": "scriptview-block-content"
    },
    "content": [
        "test"
    ]
}

const html = render(markup, {closingSingleTag: 'tag'})
console.log(html)
```

Expected (for vue to be readable):

```html
<component class="scriptview-block-content">test</component>
```

Result:

```html
<component class="scriptview-block-content"></component>
<!-- or without closingSingleTag -->
<component class="scriptview-block-content">
```

**Comment by michael-ciniawsky** [comment]
#19

**Comment by Hammster** [comment]
Thanks for the fast fix! 🥇 Will close the issue once the pull request is merged
