### ISSUE TITLE
Breaking change - node version in bugfix release

### ISSUE THREAD

**Issue by AllainPL** [posthtml/posthtml-render#34]
Hi, in one project we are using some packages that in the dependency tree use the posthtml-render. 

We just noticed our CI/CD pipeline broke because of your change in required node version in the latest bugfix update. [package.json changes](https://github.com/posthtml/posthtml-render/compare/v1.2.0...v1.2.1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

Because of legacy (what else :D) we are depending on node 8 so this "bugfix" is quite disruptive. I think that doing this kind of change in a bugfix is a bit too drastic. I would say that even in a minor release it can be a too big change. Especially when some packages are using the caret `^` notation for versions.

**Comment by anikethsaha** [comment]
I agree it should have been a major release. 
cc @Scrum .

**Comment by AllainPL** [comment]
I think the best approach would be doing asap another bugfix, reverting this, and creating a separate major one :)

**Comment by anikethsaha** [comment]
maybe completing https://github.com/posthtml/posthtml-render/pull/10 or creating a separate as that is a being inactive for a while and then doing a major release. 
yes it has to be soon and if #10  is blocking then I think it should be release without it

**Comment by AllainPL** [comment]
Another thing - the `posthtml` package looks like the release was before this change https://github.com/posthtml/posthtml/compare/v0.12.1...master but the downloaded tarball shows this change to node 10 is in there :/

**Comment by Scrum** [comment]
@AllainPL Hi, I'm glad that this package is in demand.

This [update](https://github.com/posthtml/posthtml-render/compare/v1.2.0...v1.2.1#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) I didn’t bring any changes with me that could disrupt the overall work, you can notice this on the tests that have not changed and were passed.

> CI/CD pipeline broke

Can you describe the reasons why he fell? or provide access for analysis? because changes that were made to a greater extent affect only our CI

The only option that I can only assume is that you have the setting `engine-strict=true` in `.npmrc`

**Comment by AllainPL** [comment]
> The only option that I can only assume is that you have the setting engine-strict=true in .npmrc

Yarn by default respects the `engine` field. To make it skip you need to use `yarn install --ignore-engines`.

> Can you describe the reasons why he fell?

So it failed because a package that is our dep has `posthtml-render` set to `^1.1.4` - so when it will update to `1.2.1` - it obviously breaks.

And again - doing a PATCH version release, and doing such a change doesn't make sense.
https://semver.org/#spec-item-8 - changing the engine version definitely feels like a backwards incompatible change. 

For now we have fixed the version in the `resolution` field - but it's more of a workaround than a solution.

**Comment by Scrum** [comment]
Good, because we are compatible for version 8 node, we can return this parameter, but it should not be like `Breaking change` for you, otherwise I recommend freezing versions `^1.1.4` => `1.1.4`

**Comment by Scrum** [comment]
@AllainPL publish posthtml-render@1.2.2
