### ISSUE TITLE
Missing TypeScript definition

### ISSUE THREAD

**Issue by cvrajeesh** [posthtml/posthtml-render#40]
TypeScript definition is missing for this plugin. 

I could submit a PR which include TS definition or submit it as an external definition to https://github.com/DefinitelyTyped/DefinitelyTyped

@Scrum any suggestions?

**Comment by Scrum** [comment]
> TypeScript definition is missing for this plugin.
> 
> I could submit a PR which include TS definition or submit it as an external definition to https://github.com/DefinitelyTyped/DefinitelyTyped

Hello, it will be great, also look at the existing developments https://github.com/posthtml/posthtml-render/pull/10

**Comment by cvrajeesh** [comment]
Thank you @Scrum 

Submitted a new PR #41 with the required type definitions

**Comment by Scrum** [comment]
@cvrajeesh publish v1.2.3
