### ISSUE TITLE
Case sensitivity breaks empty elements

### ISSUE THREAD

**Issue by JKC-Codes** [posthtml/posthtml-render#49]
Self closing tags which contain an upper-case character are not recognised as self closing, causing invalid HTML.

```js
const render = require('posthtml-render')

const uppercaseTree = [ { tag: 'IMG' } ]
const lowercaseTree = [ { tag: 'img' } ]

const html1 = render(uppercaseTree) // Returns: <IMG></IMG>
const html2 = render(lowercaseTree) // Returns: <img>
```

This happens with all empty HTML elements: area, base, br, col, embed, hr, img, input, link,, meta, param, source, track, wbr.

Using posthtml-render@1.4.0 in Node

**Comment by Scrum** [comment]
Thanks, I will check
